using SixLabors.ImageSharp;

namespace Neural.Onnx.Models.Yolo5.Specifications;

public static class Yolo5Specification
{
    public static Size InputSize { get; set; } = new Size(640, 640);
    
    public static string Output { get; set; } = "output";
    
    public static string[] Outputs { get; set; } = [Output];
    
    public static Yolo5Class[] Classes { get; set; } = [
        Yolo5Class.Person,
        Yolo5Class.Bicycle,
        Yolo5Class.Car,
        Yolo5Class.Motorcycle,
        Yolo5Class.Airplane,
        Yolo5Class.Bus,
        Yolo5Class.Train,
        Yolo5Class.Truck,
        Yolo5Class.Boat,
        Yolo5Class.TrafficLight,
        Yolo5Class.FireHydrant,
        Yolo5Class.StopSign,
        Yolo5Class.ParkingMeter,
        Yolo5Class.Bench,
        Yolo5Class.Bird,
        Yolo5Class.Cat,
        Yolo5Class.Dog,
        Yolo5Class.Horse,
        Yolo5Class.Sheep,
        Yolo5Class.Cow,
        Yolo5Class.Elephant,
        Yolo5Class.Bear,
        Yolo5Class.Zebra,
        Yolo5Class.Giraffe,
        Yolo5Class.Backpack,
        Yolo5Class.Umbrella,
        Yolo5Class.Handbag,
        Yolo5Class.Tie,
        Yolo5Class.Suitcase,
        Yolo5Class.Frisbee,
        Yolo5Class.Skis,
        Yolo5Class.Snowboard,
        Yolo5Class.SportsBall,
        Yolo5Class.Kite,
        Yolo5Class.BaseballBat,
        Yolo5Class.BaseballGlove,
        Yolo5Class.Skateboard,
        Yolo5Class.Surfboard,
        Yolo5Class.TennisRacket,
        Yolo5Class.Bottle,
        Yolo5Class.WineGlass,
        Yolo5Class.Cup,
        Yolo5Class.Fork,
        Yolo5Class.Knife,
        Yolo5Class.Spoon,
        Yolo5Class.Bowl,
        Yolo5Class.Banana,
        Yolo5Class.Apple,
        Yolo5Class.Sandwich,
        Yolo5Class.Orange,
        Yolo5Class.Broccoli,
        Yolo5Class.Carrot,
        Yolo5Class.HotDog,
        Yolo5Class.Pizza,
        Yolo5Class.Donut,
        Yolo5Class.Cake,
        Yolo5Class.Chair,
        Yolo5Class.Couch,
        Yolo5Class.PottedPlant,
        Yolo5Class.Bed,
        Yolo5Class.DiningTable,
        Yolo5Class.Toilet,
        Yolo5Class.Tv,
        Yolo5Class.Laptop,
        Yolo5Class.Mouse,
        Yolo5Class.Remote,
        Yolo5Class.Keyboard,
        Yolo5Class.CellPhone,
        Yolo5Class.Microwave,
        Yolo5Class.Oven,
        Yolo5Class.Toaster,
        Yolo5Class.Sink,
        Yolo5Class.Refrigerator,
        Yolo5Class.Book,
        Yolo5Class.Clock,
        Yolo5Class.Vase,
        Yolo5Class.Scissors,
        Yolo5Class.TeddyBear,
        Yolo5Class.HairDrier,
        Yolo5Class.Toothbrush
    ];
}