apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pv-claim
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /storage
          env:
            # Minio access key and secret key
            - name: MINIO_ACCESS_KEY
              value: "Gtld8JI91dkIwKpO"
            - name: MINIO_SECRET_KEY
              value: "ykTxNCXp25YFBlUHHvhbiuck32FDpruU"
            - name: MINIO_DEFAULT_BUCKETS
              value: person-detection
          ports:
            - containerPort: 9000
              hostPort: 9000
          volumeMounts:
            - name: storage
              mountPath: "/storage"
        - name: createbuckets
          image: jejikeh/nc-mc
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Wait for MinIO to start
              while ! curl -s http://minio-service:9000 >/dev/null; do
                echo 'Waiting for MinIO to start...'
                sleep 1
              done

              ./mc alias set myminio http://minio-service:9000 Gtld8JI91dkIwKpO ykTxNCXp25YFBlUHHvhbiuck32FDpruU;
              ./mc mb myminio/person-detection;
              ./mc anonymous set public myminio/person-detection;
              exit 0;
