services:
  database:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=person-detection
      - POSTGRES_USER=person-detection
      - POSTGRES_PASSWORD=person-detection
      - PGUSER=person-detection
    ports:
      - "5432:5432"
    volumes:
      - database-data:/data/db
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  database-data:
