services:
  database:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=person-detection
      - POSTGRES_USER=person-detection
      - POSTGRES_PASSWORD=person-detection
      - PGUSER=person-detection
    ports:
      - "5432:5432"
    volumes:
      - database-data:/data/db
    networks:
      - dev
    
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - dev
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=person-detection
      - MINIO_ROOT_PASSWORD=person-detection
      - MINIO_DEFAULT_BUCKETS=person-detection

networks:
  dev:
    driver: bridge

volumes:
  database-data:
  minio_data:
    driver: local
